server.port=5080
spring.application.name=cacaoselva-api

# H2 en modo archivo: los datos permanecen despues de reiniciar la API.
spring.datasource.url=jdbc:h2:file:./data/cacaoselva;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
