# Activar con: --spring.profiles.active=postgres
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cacaoselvabd}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
